version: "3.8"

services:
  recosys-cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace
      - ./datasets:/workspace/datasets:ro # Read-only datasets
      - ./models:/workspace/models
      - ./notebooks:/workspace/notebooks
      - cuda-cache:/root/.cache
    ports:
      - "8888:8888" # Jupyter
      - "6006:6006" # TensorBoard
    command: >
      bash -c "
        source activate recosys_research_cuda &&
        jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  cuda-cache:
