name: recosys_research_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12.*

  # Core scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.17.0

  # Data processing
  - h5py>=3.9.0
  - pytables>=3.8.0

  # Development tools
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - black>=23.10.0
  - flake8>=6.1.0
  - pre-commit>=3.5.0

  # Progress and utilities
  - tqdm>=4.65.0
  - psutil>=5.9.0

  # CUDA toolkit for Linux
  - cudatoolkit=12.1
  - nvidia::cuda-toolkit=12.1

  # PyTorch with CUDA support
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision>=0.15.0
  - pytorch::torchaudio>=2.0.0

  # ML experiment tracking
  - wandb>=0.16.0
  - tensorboard>=2.15.0

  # TensorFlow with CUDA support
  - tensorflow-gpu>=2.15.0,<3.0.0
  
  # Keras (included with TensorFlow but explicitly specified)
  - keras>=3.0.0

  # Pip dependencies for packages not available via conda
  - pip
  - pip:
      # PyTorch Geometric with CUDA support
      - torch-geometric>=2.4.0
      - torch-sparse
      - torch-scatter
      - torch-cluster

      # Additional graph libraries
      - ogb>=1.3.6
      - torchmetrics>=1.2.0
      - torch-geometric-temporal

      # Development dependencies
      - aiohappyeyeballs>=2.4.3
      - aiohttp>=3.10.0
      - beautifulsoup4>=4.13.0
      - boto3>=1.35.0
      - geopandas>=1.0.0
      - google-ai-generativelanguage>=0.6.0
      - langchain-core>=0.3.0
      - openai>=1.54.0
      - supabase>=2.10.0
